### ISSUE TITLE
Implement batch feature annotator

### ISSUE THREAD

**Issue by axiomabsolute** [axiomabsolute/gramme#1]
Implement a batch-oriented feature extractor (annotator) for generic text documents.

## Subtasks

- [x] Implement shared primitive structures
    - [x] Span
    - [x] Region
    - [x] Cursor
- [x] Implement annotator primitives
    - [x] Annotation
- [x] Implement general text feature annotator
    - [x] Buffer annotator
    - [x] Line annotator
    - [x] Word annotator
- [x] Batch annotator infrastructure
    - [x] Define annotator interface
    - [x] Define pipeline for array of annotators. In particular, expect at least a general annotator + doctype specific annotator
- [ ] Basic annotator index
    - [x] Get annotations at cursor
    - [x] Filter by type tag
    - [ ] ~Persist on disk~ No need for now
