### ISSUE TITLE
Implement Command Language Parser & Interpreter

### ISSUE THREAD

**Issue by axiomabsolute** [axiomabsolute/gramme#2]
Responsible for taking raw input and translating it into a sequence of commands. Commands rely on editor for storing intermediate state (e.g. in registers).

## Subtasks

- [ ] Parsing
    - [ ] Lexer
    - [ ] Parser
- [ ] Batch (non-interactive) Interpreter
    - [ ] Consume commands one at a time
    - [ ] Apply in sequence
    - [ ] Editor instance for all intermediate state
- [ ] Test Command
    - [ ] Accept input file path, command file path, and output file path as inputs
    - [ ] Read input file, initialize new editor instance
    - [ ] Read commands, parse
    - [ ] Interpret commands
    - [ ] Save output
